/* eslint-disable @next/next/no-img-element */
"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Nn0U9pQ6PvO
 */
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import QRCode from "qrcode";
import { useEffect, useRef, useState } from "react";
import ReactToPrint from "react-to-print";

const regex = /senseBox:bike \[([A-Fa-f0-9]+)\]/;

export function QRGeneratorForm() {
  const [text, setText] = useState<string>();
  const [qrCode, setQRCode] = useState("");

  const ref = useRef<HTMLDivElement>(null);

  const svgString = `<svg viewBox="0 0 128 160">
  <path d="M0,0 L128,0 L128,160 L0,160 Z" fill="#fff" />
  ${qrCode}
  <text
    text-anchor="middle"
    x="64"
    y="142"
    fill="#000"
    font-size="8"
    font-weight="600"
  >
    ${text?.split(" ")[0]}
  </text>
  <text
    text-anchor="middle"
    x="64"
    y="154"
    fill="#000"
    font-size="8"
    font-weight="600"
  >
    ${text?.split(" ")[1]}
  </text>
</svg>`;

  useEffect(resetQRCode, []);

  useEffect(() => {
    if (!text) {
      resetQRCode();
      return;
    }

    QRCode.toString(text, { type: "svg" }, (err, str) => {
      setQRCode(str);
    });
  }, [text]);

  function resetQRCode() {
    QRCode.toString(
      "senseBox:bike [ABC123ABC123]",
      {
        type: "svg",
        color: {
          dark: "#aaaaaa",
          light: "fff",
        },
      },
      (err, str) => {
        setQRCode(str);
      }
    );
  }

  async function handleReadFromSerialClick() {
    try {
      const port = await navigator.serial.requestPort({
        filters: [{ usbVendorId: 1240 }],
      });
      console.log(await port.getInfo());
      await port.open({ baudRate: 115200 });
      while (port.readable) {
        const reader = port.readable.getReader();
        try {
          while (true) {
            const { value, done } = await reader.read();
            if (done) {
              // |reader| has been canceled.
              break;
            }
            const text = new TextDecoder().decode(value);

            const match = text.match(regex);
            if (match) {
              const id = match[1];
              setText(`senseBox:bike [${id}]`);

              await port.close();
              await port.forget();
              break;
            }
          }
        } catch (error) {
          // Handle |error|...
        } finally {
          reader.releaseLock();
        }
      }
    } catch (error) {
      console.error(error);
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-2xl">QR Code Generator</CardTitle>
        <CardDescription>
          Enter the text you want to convert to a QR code.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex items-center flex-col w-full gap-4">
          <div className="space-y-2 w-full">
            <Label htmlFor="qr-text">Text</Label>
            <Input
              id="qr-text"
              placeholder="Enter text here"
              required
              defaultValue={text}
              onChange={(e) => setText(e.target.value)}
              type="text"
            />
          </div>
          <p className="text-sm">or</p>
          <Button className="w-full" onClick={handleReadFromSerialClick}>
            Read from Serial
          </Button>
        </div>
        <div className="space-y-2">
          <Label htmlFor="qr-code">Generated QR Code</Label>
          <div className="w-full bg-gray-100 rounded-lg flex items-center justify-center p-4">
            <div
              className="bg-black p-2 rounded-lg w-fit flex flex-col items-center"
              ref={ref}
            >
              <img
                alt="Generated QR Code"
                className="object-contain w-64 h-64 aspect-square"
                id="qr-code"
                style={{
                  // aspectRatio: "256/256",
                  objectFit: "cover",
                }}
                width="256"
                src={`data:image/svg+xml;utf8,${encodeURIComponent(qrCode)}`}
              />
              <span className="text-white pt-2 pb-1 text-lg font-semibold whitespace-pre-wrap max-w-[16rem] text-center">
                {text}
              </span>
            </div>
          </div>
        </div>
      </CardContent>
      <CardFooter className="gap-2">
        {ref.current && (
          <ReactToPrint
            bodyClass="print-agreement"
            content={() => ref.current}
            trigger={() => <Button className="w-full">Print QR Code</Button>}
          />
        )}
        <a
          href={`data:application/octet-stream;utf8,${encodeURIComponent(
            svgString
          )}`}
          download={`${text}.svg`}
        >
          <Button className="w-full">Download as image</Button>
        </a>
      </CardFooter>
    </Card>
  );
}
