/* eslint-disable @next/next/no-img-element */
"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Nn0U9pQ6PvO
 */
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import QRCode from "qrcode";
import { useEffect, useRef, useState } from "react";
import ReactToPrint from "react-to-print";

export function QRGeneratorForm() {
  const [text, setText] = useState<string>();
  const [qrCode, setQRCode] = useState("");

  const ref = useRef<HTMLDivElement>(null);

  useEffect(resetQRCode, []);

  useEffect(() => {
    if (!text) {
      resetQRCode();
      return;
    }

    QRCode.toString(text, { type: "svg" }, (err, str) => {
      setQRCode(str);
    });
  }, [text]);

  function resetQRCode() {
    QRCode.toString(
      "senseBox:bike [ABC123ABC123]",
      {
        type: "svg",
        color: {
          dark: "#aaaaaa",
          light: "fff",
        },
      },
      (err, str) => {
        setQRCode(str);
      }
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-2xl">QR Code Generator</CardTitle>
        <CardDescription>
          Enter the text you want to convert to a QR code.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="qr-text">Text</Label>
          <Input
            id="qr-text"
            placeholder="Enter text here"
            required
            defaultValue={text}
            onChange={(e) => setText(e.target.value)}
            type="text"
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="qr-code">Generated QR Code</Label>
          <div className="w-full bg-gray-100 rounded-lg flex items-center justify-center p-4">
            <div
              className="bg-black p-2 rounded-lg w-fit flex flex-col items-center"
              ref={ref}
            >
              <img
                alt="Generated QR Code"
                className="object-contain w-64 h-64"
                height="256"
                id="qr-code"
                style={{
                  aspectRatio: "256/256",
                  objectFit: "cover",
                }}
                width="256"
                src={`data:image/svg+xml;utf8,${encodeURIComponent(qrCode)}`}
              />
              <span className="text-white pt-2 pb-1 text-lg font-semibold whitespace-pre-wrap max-w-[16rem] text-center">
                {text}
              </span>
            </div>
          </div>
        </div>
      </CardContent>
      <CardFooter>
        {ref.current && (
          <ReactToPrint
            bodyClass="print-agreement"
            content={() => ref.current}
            trigger={() => <Button className="w-full">Print QR Code</Button>}
          />
        )}
      </CardFooter>
    </Card>
  );
}
